version: '3'

services:
    web:
        image: agenda:latest
        volumes:
            - sqlite3-db:/sqlite3-db
        environment:
            - WORDPRESS_DB_USER=manager
            - WORDPRESS_DB_PASSWORD=secret
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80

volumes:
    sqlite3-db:
